version: "3.7"

services:
  traefik:
    image: traefik:2.6.6
    container_name: proxy_load_balancer
    networks:
      - traefik-proxy-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-proxy-network"
      - "--entrypoints.web.address=:80"
      - "--accesslog=true"
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"

  mariadb:
    image: bitnami/mariadb:latest
    labels:
      - "traefik.enable=false"
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_PASSWORD=bitnami
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - database

  moodle:
    # image: bitnami/moodle:3.11.7
    image: bitnami/moodle:4
    environment:
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=bitnami
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 8000:8080
    depends_on:
      - mariadb
    networks:
      - database
      - traefik-proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.moodle.loadbalancer.server.port=8080"
      # - "traefik.http.routers.moodle.rule=HostRegexp(`{catchall:.*}`)"
      - "traefik.http.routers.moodle.rule=Host(`moodle.localhost`)"
      - "traefik.docker.network=traefik-proxy-network"

networks:
  database:
    driver: bridge
  traefik-proxy-network:
    external: true
